Repository Kernel360/KBE5_DANMUJI_FE, pull requests merged in 2025-07, with the labels that each got.

#172 [Feature] 문의사항 세부 수정
  src/features/inquiry/pages/InquiryDetailPage.tsx
Labels: ✨ 기능 추가, 정인 🐻

#192 [Feature] 프로젝트 생성 시 업체등록 및 멤버 등록 모달 연결
  src/features/project/components/CompanyMemberSelectModal.tsx
Labels: ✨ 기능 추가, 진효 🐰

#194 [Feature] 회원 대시보드 프로젝트 조회 실제 데이터 연동
  src/features/project/components/Card/ProjectCard.tsx
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/services/projectService.ts
  src/features/project/types/Types.ts
  src/features/user/pages/dashboard/UserDashboardPage.tsx
  src/features/user/pages/dashboard/components/ProjectStatusSection.tsx
  src/features/user/pages/dashboard/components/WarningProjectsSection.tsx
Labels: ✨ 기능 추가, 유진 🐱

#205 [Feature] 게시글 복구 기능 개선 및 UI/UX 반영, 알림/토스트/모달 동기화, 복구 필터 연동 처리
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/admin/pages/ActivityLogPage.tsx
  src/features/admin/services/activityLogService.ts
  src/features/admin/types/activityLog.ts
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/components/FormModal/components/FileUploadSection.tsx
  src/features/project-d/services/postService.ts
  src/features/project/services/projectService.ts
  src/features/user/pages/dashboard/components/MentionedPostsSection.tsx
  src/layouts/Header/notification/NotificationDropdown.tsx
Labels: ✨ 기능 추가, 승우 🐯

#207 [Fix] 잘못된 권한 확인
  src/routes/AppRoutes.tsx
Labels: 진효 🐰, 🐞 버그

#213 [Fix] status enum 변수명 변경
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/pages/ProjectListPage.tsx
Labels: 진효 🐰, 🐞 버그

#211 [Feature] 이슈테스트 이후 발견된 버그 수정
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/admin/pages/ActivityLogPage.tsx
  src/features/board/components/Post/components/DetailModal/PostAttachments.tsx
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/company/pages/CompanyPage.tsx
  src/features/inquiry/InquiryPage.tsx
  src/features/inquiry/UserInquiryPage.tsx
  src/features/project-d/pages/ProjectPostPage.tsx
  src/features/project-d/services/postService.ts
  src/features/project-d/types/post.ts
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/Board/ProjectBoardPagination.tsx
  src/features/project/components/ProjectCreateModal.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/services/projectService.ts
  src/features/project/types/Types.ts
  src/features/user/pages/MemberPage.tsx
  src/features/user/pages/dashboard/components/LatestPostsSection.tsx
  src/features/user/pages/dashboard/components/MentionedPostsSection.tsx
  src/features/user/pages/dashboard/components/PriorityPostsSection.tsx
  src/features/user/pages/dashboard/styled/UserDashboardPage.styled.ts
Labels: ✨ 기능 추가, 승우 🐯, 🐞 버그, 🧙‍♂️ 해결

#217 [Feature] 프로젝트 및 회사 복구 기능에 대한 API 연동
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/admin/pages/ActivityLogPage.tsx
  src/features/admin/services/activityLogService.ts
  src/features/project/pages/ProjectListPage.tsx
Labels: ✨ 기능 추가, 승우 🐯

#220 [Feature] 회사별 회원 수 표시
  src/features/project/components/CompanyMemberSelectModal.tsx
  src/features/project/components/Progress/StepOrderModal.tsx
Labels: ✨ 기능 추가, 진효 🐰

#228 [Hotfix] 각종 입력 제한 두기
  src/App.css
  src/features/admin/pages/DashboardPage.tsx
  src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
  src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
  src/features/company/pages/CompanyPage.tsx
  src/features/inquiry/components/InquiryRegisterModal/InquiryRegisterModal.tsx
  src/features/inquiry/pages/InquiryDetailPage.tsx
  src/features/user/components/MemberEditModal/MemberEditModal.tsx
  src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
  src/features/user/pages/MemberPage.tsx
Labels: ✨ 기능 추가, 정인 🐻

#230 [Feature] 체크리스트 기능 개선 및 디자인 리팩터링
  package-lock.json
  package.json
  src/features/admin/types/activityLog.ts
  src/features/project-d/pages/ProjectDetailPage.styled.ts
  src/features/project-d/pages/ProjectDetailPage.tsx
  src/features/project/components/Checklist/ChecklistBoard.styled.ts
  src/features/project/components/Checklist/ChecklistCard.tsx
  src/features/project/components/Checklist/ChecklistCreateModal.styled.ts
  src/features/project/components/Checklist/ChecklistCreateModal.tsx
  src/features/project/components/Checklist/ChecklistDetailModal.styled.ts
  src/features/project/components/Checklist/ChecklistDetailModal.tsx
  src/features/project/components/Checklist/KanbanBoard.tsx
  src/features/project/pages/ProjectDetailPage.styled.ts
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/services/projectService.ts
  src/features/user/pages/dashboard/components/MentionedPostsSection.tsx
  src/features/user/services/userService.ts
  src/hooks/useNotification.ts
  src/layouts/Header/notification/NotificationDropdown.tsx
  src/layouts/Topbar/Topbar.types.ts
Labels: ♻️ 리팩토링, ✨ 기능 추가, 유진 🐱, 🎨 스타일

#232 [Hotfix] 사용자 문의사항 페이지 검토
  src/features/inquiry/InquiryPage.tsx
  src/features/inquiry/UserInquiryPage.tsx
Labels: ✨ 기능 추가, 정인 🐻

#238 [Merge] 게시글/댓글 생성 및 수정 시 길이 제한 검증 에러 메시지 추가, 체크리스트 관련 UI/기능 개선 및 필터 초기화 기능 추가
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/admin/pages/ActivityLogPage.tsx
  src/features/admin/pages/DashboardPage.tsx
  src/features/admin/services/activityLogService.ts
  src/features/board/components/Comment/components/CommentForm.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/inquiry/InquiryPage.tsx
  src/features/inquiry/UserInquiryPage.tsx
  src/features/project/components/Board/ProjectBoardFilters.tsx
  src/features/project/components/Card/ProjectCard.styled.ts
  src/features/project/components/Checklist/ChecklistCreateModal.styled.ts
  src/features/project/components/Checklist/ChecklistCreateModal.tsx
  src/features/project/components/Checklist/KanbanBoard.tsx
  src/features/project/components/CompanyMemberSelectModal.tsx
  src/features/project/components/Header/ProjectHeader.tsx
  src/features/project/components/List/ProjectFilterBar.styled.ts
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/components/Progress/ProjectProgress.tsx
  src/features/project/components/Progress/StepOrderModal.tsx
  src/features/project/components/ProjectCreateModal.styled.ts
  src/features/project/components/ProjectCreateModal.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.tsx
  src/features/user/pages/dashboard/components/ProjectStatusSection.tsx
Labels: ✨ 기능 추가, 승우 🐯, 🎨 스타일

#241 [Feature] 필터링 정상화(필터 선택 시 api요청)
  src/features/inquiry/InquiryPage.tsx
  src/features/inquiry/UserInquiryPage.tsx
  src/features/user/pages/MemberPage.tsx
Labels: ✨ 기능 추가, 정인 🐻

#242 [Style] UI 개선 및 알림 연동 등 체크리스트 기능 개선 작업
  src/features/admin/pages/DashboardPage.tsx
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/Board/ProjectBoardFilters.tsx
  src/features/project/components/Checklist/ChecklistBoard.styled.ts
  src/features/project/components/Checklist/ChecklistDetailModal.tsx
  src/features/project/components/Checklist/KanbanBoard.tsx
  src/features/project/components/CompanyMemberSelectModal.tsx
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/components/Progress/StepOrderModal.tsx
  src/features/project/components/ProjectCreateModal.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/user/pages/MemberPage.tsx
  src/features/user/pages/dashboard/components/MentionedPostsSection.tsx
  src/features/user/pages/dashboard/components/ProjectStatusSection.tsx
  src/features/user/pages/dashboard/components/WarningProjectsSection.tsx
  src/features/user/pages/dashboard/styled/UserDashboardPage.styled.ts
  src/layouts/Header/profile/UserProfile.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: ✨ 기능 추가, 승우 🐯, 🎨 스타일

#243 Style/239 UI
  src/features/company/components/CompanyDetailModal/CompanyDetailModal.styled.ts
  src/features/inquiry/components/InquiryRegisterModal/InquiryRegisterModal.tsx
  src/features/project-d/pages/ProjectDetailPage.tsx
  src/features/project/components/Checklist/ChecklistCreateModal.styled.ts
  src/features/project/components/Checklist/ChecklistCreateModal.tsx
  src/features/project/components/Checklist/ChecklistDetailModal.styled.ts
  src/features/project/components/Checklist/ChecklistDetailModal.tsx
  src/features/project/components/Checklist/KanbanBoard.tsx
  src/features/project/components/Header/ProjectHeader.styled.ts
Labels: ✨ 기능 추가, 승우 🐯, 🎨 스타일

#248 [Feat] 프로젝트 편집 시 멤버 수정 가능
  src/features/project/components/CompanyMemberSelectModal.tsx
Labels: ✨ 기능 추가, 진효 🐰
