Repository Kernel360/KBE5_DANMUJI_FE, pull requests merged in 2025-06, with the labels that each got.

#18 [Feature] login/logout 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/danmuji_logo.png
  src/features/auth/components/LeftPanel.tsx
  src/features/auth/components/LoginForm.tsx
  src/features/auth/pages/LoginPage.styled.ts
  src/features/auth/pages/LoginPage.tsx
  src/layouts/Footer/Footer.styled.ts
  src/layouts/Footer/Footer.tsx
  src/layouts/Header/ProfileDropdown.tsx
  src/pages/LoginPage.tsx
  vite.config.ts
Labels: ✨ 기능 추가, 유진 🐱

#24 [Feature] 실제 정보 조회 및 디자인
  src/contexts/AuthContexts.tsx
  src/layouts/Header/ProfileDropdown.tsx
  src/layouts/Header/UserProfile.styled.ts
  src/layouts/Header/UserProfile.tsx
  src/layouts/Sidebar/Sidebar.styles.ts
  src/layouts/Sidebar/Sidebar.tsx
Labels: ✨ 기능 추가, 유진 🐱, 🎨 스타일

#33 [Feature] 로그인 시 axios 사용으로 수정
  src/features/auth/pages/LoginPage.tsx
  vite.config.ts
Labels: ♻️ 리팩토링, 유진 🐱

#38 [Feature] 정적 파일 public 하위로 수정
  public/assets/Chart-Icon.png
  public/assets/Check-Icon.png
  public/assets/Lock-Icon.png
  public/assets/Success-Icon.png
  public/assets/Team-Icon.png
  public/assets/danmuji-logo.png
  public/assets/danmuji_logo.png
  public/assets/logo_v1.png
  public/assets/react.svg
  src/features/auth/components/DanmujiLogo.tsx
  src/features/auth/components/LeftPanel.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: ✨ 기능 추가, 유진 🐱

#41 [Feature] 로그인 시 액세스 토큰 헤더에서 추출 및 수정 작업
  index.html
  public/assets/danmuji_favicon.png
  public/vite.svg
  src/api/axios.ts
  src/contexts/AuthContexts.tsx
  src/features/auth/components/DanmujiLogo.tsx
  src/features/auth/components/LeftPanel.tsx
  src/features/auth/pages/ForgotPasswordPage.tsx
  src/features/auth/pages/LoginPage.tsx
  vite.config.ts
Labels: ♻️ 리팩토링, ✨ 기능 추가, 유진 🐱

#43 [Refactor] 오류 수정
  src/App.tsx
  vite.config.ts
Labels: ♻️ 리팩토링, ❌ 삭제, 유진 🐱

#45 [Feature] 정적 파일 서빙 허용
  index.html
  public/src/assets/Chart-Icon.png
  public/src/assets/Check-Icon.png
  public/src/assets/Lock-Icon.png
  public/src/assets/Success-Icon.png
  public/src/assets/Team-Icon.png
  public/src/assets/danmuji-logo.png
  public/src/assets/danmuji_favicon.png
  public/src/assets/danmuji_logo.png
  public/src/assets/logo_v1.png
  src/api/axios.ts
  src/assets/react.svg
  src/features/auth/components/LeftPanel.tsx
  src/layouts/Sidebar/Sidebar.tsx
  vite.config.ts
Labels: ⚙️ 기타 작업, ✨ 기능 추가, 유진 🐱

#46 [Refactor] 정적 파일 수정
  index.html
  public/Chart-Icon.png
  public/Check-Icon.png
  public/Lock-Icon.png
  public/Success-Icon.png
  public/Team-Icon.png
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/danmuji-logo.png
  public/danmuji_favicon.png
  public/danmuji_logo.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/logo_v1.png
  public/site.webmanifest
  src/features/auth/components/DanmujiLogo.tsx
  src/features/auth/components/LeftPanel.tsx
  src/features/auth/pages/ForgotPasswordPage.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: ♻️ 리팩토링, 유진 🐱

#49 [Fix] 버그 수정
  vercel.json
Labels: 유진 🐱

#56 Feature/55
  src/features/board/components/PostDetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/QuestionAnswerModal/QuestionAnswerModal.tsx
  src/features/project/components/ProjectPostDetailModal.tsx
  src/features/project/components/ProjectPostDetailModal/ProjectPostDetailModal.styled.ts
  src/features/project/components/ProjectPostDetailModal/ProjectPostDetailModal.tsx
  src/features/project/types/post.ts
  src/features/project/types/question.ts
Labels: ✨ 기능 추가, 승우 🐯

#59 [Feature] 회원의 프로젝트 관리 페이지 구현
  src/App.tsx
  src/features/auth/pages/LoginPage.tsx
  src/features/project/pages/AdminProjectPage.styled.ts
  src/features/project/pages/AdminProjectPage.tsx
  src/features/project/pages/CompletedProject.tsx
  src/features/project/pages/CreateProjectPage.tsx
  src/features/project/pages/InProgressProject.tsx
  src/features/project/pages/ProjectDetailPage.styled.ts
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/UserProjectPage.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: ✨ 기능 추가, ❌ 삭제, 진효 🐰

#69 [Feature] 푸터 하단 고정
  src/App.styled.ts
  src/App.tsx
  src/features/admin/pages/DashboardPage.styled.ts
  src/layouts/Footer/Footer.styled.ts
Labels: 유진 🐱, 🎨 스타일

#70 [Feature] 프로젝트 수정 페이지 및 단계 승인자, 승인상태 변경
  src/App.tsx
  src/features/project/pages/CompletedProject.tsx
  src/features/project/pages/CreateProjectPage.tsx
  src/features/project/pages/EditProjectPage.tsx
  src/features/project/pages/InProgressProject.tsx
  src/features/project/pages/ProjectDetailPage.styled.ts
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/UserProjectPage.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: ♻️ 리팩토링, ✨ 기능 추가, 진효 🐰, 🎨 스타일

#71 [Feature] 정보 조회 페이지 구현
  src/App.tsx
  src/contexts/AuthContext.tsx
  src/contexts/AuthContexts.tsx
  src/features/auth/pages/LoginPage.tsx
  src/features/board/components/AnswerDetailModal/AnswerDetailModal.tsx
  src/features/board/components/PostDetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/QuestionAnswerModal/QuestionAnswerModal.tsx
  src/features/project/components/CommentList/CommentList.tsx
  src/features/project/pages/CompletedProject.tsx
  src/features/project/pages/InProgressProject.tsx
  src/features/project/pages/ProjectPostPage.tsx
  src/features/project/pages/UserProjectPage.tsx
  src/features/user/pages/UserProfilePage.tsx
  src/features/user/pages/styles/UserProfilePage.styled.ts
  src/hooks/useAuth.ts
  src/layouts/Header/ProfileDropdown.tsx
  src/layouts/Header/UserProfile.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: ✨ 기능 추가, 유진 🐱, 🎨 스타일

#76 [Feature] 프로젝트 목록 페이지 페이징 적용
  src/features/project/pages/AdminProjectPage.tsx
  src/features/project/pages/CreateProjectPage.tsx
  src/features/project/pages/EditProjectPage.tsx
  src/features/project/pages/InProgressProject.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/UserProjectPage.tsx
Labels: ✨ 기능 추가, 진효 🐰

#78 [Feature] 회원 생성 시 text 파일 저장 및 알림 서비스 구현
  package-lock.json
  package.json
  src/App.tsx
  src/AppRoutes.tsx
  src/components/NotificationDropdown.tsx
  src/features/user/pages/MemberPage.tsx
  src/hooks/useNotification.ts
  src/layouts/Header/NotificationDropdown.styled.ts
  src/layouts/Header/NotificationDropdown.tsx
  src/layouts/Topbar/Topbar.tsx
  src/layouts/Topbar/Topbar.types.ts
Labels: ✨ 기능 추가, 유진 🐱

#80 [Feature] 알림 서비스 수정
  src/hooks/useNotification.ts
  src/layouts/Header/NotificationDropdown.tsx
Labels: ⚙️ 기타 작업, 유진 🐱

#88 design: 전체 폰트 변경 (#87)
  src/index.css
Labels: 유진 🐱, 🎨 스타일

#96 [Refactor] 프로젝트 구조 리팩토링
  src/App.tsx
  src/features/board/components/Answer/components/AnswerItem.tsx
  src/features/board/components/Answer/hooks/useAnswerUtils.tsx
  src/features/board/components/Answer/pages/AnswerDetailModal.tsx
  src/features/board/components/Comment/components/CommentItem.tsx
  src/features/board/components/Comment/components/CommentList.tsx
  src/features/board/components/Comment/hooks/useCommentUtils.tsx
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/components/FormModal/components/PostFormFields.tsx
  src/features/board/components/Post/pages/PostListPage.tsx
  src/features/board/components/Question/components/QuestionAnswerModal/QuestionAnswerModal.tsx
  src/features/board/components/Question/components/QuestionAnswerModal/components/PostInfo.tsx
  src/features/board/components/Question/components/QuestionAnswerModal/components/QuestionForm.tsx
  src/features/board/components/Question/components/QuestionAnswerModal/components/QuestionItem.tsx
  src/features/board/components/Question/components/QuestionAnswerModal/components/QuestionList.tsx
  src/features/project-d/components/ProjectEditModal/ProjectEditModal.tsx
  src/features/project-d/components/ProjectEditModal/index.ts
  src/features/project-d/pages/AdminProjectPage.styled.ts
  src/features/project-d/pages/AdminProjectPage.tsx
  src/features/project-d/pages/CompletedProject.tsx
  src/features/project-d/pages/CreateProjectPage.tsx
  src/features/project-d/pages/CreateProjectpage.styled.ts
  src/features/project-d/pages/EditProjectPage.tsx
  src/features/project-d/pages/InProgressProject.tsx
  src/features/project-d/pages/MemberProjectPage.tsx
  src/features/project-d/pages/ProjectDetailPage.styled.ts
  src/features/project-d/pages/ProjectDetailPage.tsx
  src/features/project-d/pages/ProjectPage.styled.ts
  src/features/project-d/pages/ProjectPage.tsx
  src/features/project-d/pages/ProjectPostPage.styled.ts
  src/features/project-d/pages/ProjectPostPage.tsx
  src/features/project-d/pages/UserProjectPage.tsx
  src/features/project-d/services/postService.ts
  src/features/project-d/services/questionService.ts
  src/features/project-d/types/post.ts
  src/features/project-d/types/question.ts
  src/features/project/components/Board/ProjectBoard.styled.ts
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/Card/ProjectCard.styled.ts
  src/features/project/components/Card/ProjectCard.tsx
  src/features/project/components/Header/ProjectHeader.styled.ts
  src/features/project/components/Header/ProjectHeader.tsx
  src/features/project/components/List/ProjectFilterBar.styled.ts
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/components/MemberList/ProjectMemberList.styled.ts
  src/features/project/components/MemberList/ProjectMemberList.tsx
  src/features/project/components/Progress/ProjectProgress.styled.ts
  src/features/project/components/Progress/ProjectProgress.tsx
  src/features/project/pages/Post.styled.ts
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.styled.ts
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/types/Types.ts
  src/layouts/Sidebar/Sidebar.tsx
  src/routes/AppRoutes.tsx
  src/routes/routs
Labels: ♻️ 리팩토링, 유진 🐱, 🎨 스타일

#100 [Style] 프로젝트 목록, 프로젝트 상태, 게시글 목록 ui 개편
  src/features/project-d/pages/AdminProjectPage.styled.ts
  src/features/project-d/pages/ProjectDetailPage.styled.ts
  src/features/project-d/pages/ProjectDetailPage.tsx
  src/features/project/components/Board/ProjectBoard.styled.ts
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/Card/ProjectCard.styled.ts
  src/features/project/components/Card/ProjectCard.tsx
  src/features/project/components/Header/ProjectHeader.styled.ts
  src/features/project/components/Header/ProjectHeader.tsx
  src/features/project/components/List/ProjectFilterBar.styled.ts
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/components/Progress/ProjectProgress.styled.ts
  src/features/project/components/Progress/ProjectProgress.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.styled.ts
  src/features/project/pages/ProjectListPage.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: 승우 🐯, 🎨 스타일

#104 [Feature] 프로젝트(일부), 게시글 api 연동 및 ui 수정
  src/features/board/components/Comment/components/CommentItem.tsx
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/components/FormModal/components/PostFormActions.tsx
  src/features/board/components/Post/components/FormModal/components/PostFormFields.tsx
  src/features/board/components/Post/pages/PostListPage.tsx
  src/features/board/components/Post/styles/PostFormModal.styled.ts
  src/features/board/components/Post/styles/PostListPage.styled.ts
  src/features/board/components/Post/styles/ProjectPostDetailModal.styled.ts
  src/features/company/components/CompanyFilterBar.tsx
  src/features/project-d/services/postService.ts
  src/features/project-d/types/post.ts
  src/features/project/components/Board/ProjectBoard.styled.ts
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/Header/ProjectHeader.tsx
  src/features/project/components/Progress/ProjectProgress.styled.ts
  src/features/project/components/Progress/ProjectProgress.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/services/commentService.ts
  src/features/project/services/projectService.ts
  src/features/project/types/Types.ts
Labels: ✨ 기능 추가, 승우 🐯, 🎨 스타일

#108 [Style] 프로젝트,게시판 ui 수정 및 회원관리 페이지 ui 수정, 토스트알림으로 전역에러 표시 추가
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/features/auth/pages/ForgotPasswordPage.tsx
  src/features/auth/pages/LoginPage.tsx
  src/features/auth/pages/ResetPasswordPage.tsx
  src/features/board/components/Answer/styles/AnswerForm.styled.ts
  src/features/board/components/Comment/styles/CommentForm.styled.ts
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/FormModal/FullScreenContentEditor.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/components/FormModal/components/ContentEditorSection.tsx
  src/features/board/components/Post/components/FormModal/components/FileUploadSection.tsx
  src/features/board/components/Post/styles/PostFormModal.styled.ts
  src/features/board/components/Post/styles/PostListPage.styled.ts
  src/features/board/components/Post/styles/ProjectPostDetailModal.styled.ts
  src/features/board/components/Question/styles/QuestionAnswerModal.styled.ts
  src/features/board/pages/DashboardPage.tsx
  src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
  src/features/company/pages/CompanyPage.tsx
  src/features/project/components/Header/ProjectHeader.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/user/components/MemberEditModal/MemberEditModal.styled.ts
  src/features/user/components/MemberEditModal/MemberEditModal.tsx
  src/features/user/components/MemberRegisterModal/MemberRegisterModal.styled.ts
  src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
  src/features/user/pages/MemberDetailPage.tsx
  src/features/user/pages/MemberPage.tsx
  src/hooks/useNotification.ts
  src/styles/common/LoadingSpinner.styled.ts
  src/utils/errorHandler.ts
  수정상세모달
Labels: ♻️ 리팩토링, ✨ 기능 추가, 승우 🐯

#113 [Hotfix] 게시글 관련 오류 수정, 컴포넌트 분리, user role에 따른 라우팅 경로 추가
  src/components/ClickableMentionedUsername.tsx
  src/components/MentionSuggestions.tsx
  src/components/MentionTextArea.tsx
  src/components/UserProfileDropdown.tsx
  src/features/board/components/Answer/hooks/useAnswerUtils.tsx
  src/features/board/components/Answer/pages/AnswerDetailModal.tsx
  src/features/board/components/Comment/hooks/useCommentUtils.tsx
  src/features/board/components/Comment/styles/CommentActions.styled.ts
  src/features/board/components/Post/components/DetailModal/CommentForm.tsx
  src/features/board/components/Post/components/DetailModal/CommentItem.tsx
  src/features/board/components/Post/components/DetailModal/CommentSection.tsx
  src/features/board/components/Post/components/DetailModal/PostAttachments.tsx
  src/features/board/components/Post/components/DetailModal/PostContent.tsx
  src/features/board/components/Post/components/DetailModal/PostHeader.tsx
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/DetailModal/ReplyItem.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/styles/ProjectPostDetailModal.styled.ts
  src/features/board/pages/DashboardPage.tsx
  src/features/project-d/pages/CreateProjectPage.tsx
  src/features/project-d/pages/EditProjectPage.tsx
  src/features/project-d/types/question.ts
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/services/projectService.ts
  src/features/project/types/Types.ts
  src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
  src/hooks/useMention.ts
  src/routes/AppRoutes.tsx
  src/utils/errorHandler.ts
  src/utils/mentionUtils.tsx
Labels: ♻️ 리팩토링, 승우 🐯

#118 [Feature] 사이드바 디자인 변경
  src/layouts/Sidebar/MenuItem.styled.ts
  src/layouts/Sidebar/MenuItem.tsx
  src/layouts/Sidebar/Sidebar.styles.ts
Labels: 유진 🐱, 🎨 스타일

#120 [Feature] 프로젝트 생성 모달 추가(#98)
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/services/projectService.ts
Labels: ✨ 기능 추가, 진효 🐰

#125 [Feature/97] 회원 대시보드 페이지 UI 개선 및 기능 추가
  package-lock.json
  package.json
  src/features/user/pages/dashboard/UserDashboardPage.tsx
  src/features/user/pages/dashboard/components/LatestPostsSection.tsx
  src/features/user/pages/dashboard/components/MentionedPostsSection.tsx
  src/features/user/pages/dashboard/components/PriorityPostsSection.tsx
  src/features/user/pages/dashboard/components/ProjectStatusSection.tsx
  src/features/user/pages/dashboard/components/WarningProjectsSection.tsx
  src/features/user/pages/dashboard/styled/UserDashboardPage.styled.ts
  src/features/user/pages/profile/UserProfilePage.tsx
  src/features/user/pages/profile/styled/UserProfilePage.styled.ts
  src/layouts/Sidebar/Sidebar.tsx
  src/pages/user/UserDashboardCards.styled.tsx
  src/pages/user/UserDashboardCards.tsx
  src/pages/user/styled.tsx
  src/pages/user/userDashboard.tsx
  src/routes/AppRoutes.tsx
Labels: ♻️ 리팩토링, 유진 🐱, 🎨 스타일

#129 [Hotfix] 게시글타입이 질문이 없고 공지로 잘못 매핑돼있는 문제를 해결
  src/features/board/components/Post/components/DetailModal/PostHeader.tsx
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/components/FormModal/components/PostFormFields.tsx
  src/features/board/components/Post/pages/PostListPage.tsx
  src/features/project-d/services/postService.ts
  src/features/project-d/types/post.ts
  src/features/project/components/Board/ProjectBoard.styled.ts
  src/features/project/components/Board/ProjectBoard.tsx
Labels: 승우 🐯, 🐞 버그, 🧙‍♂️ 해결

#133 [Feature] 프로젝트 생성 api 연결
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/services/projectService.ts
Labels: ✨ 기능 추가, 진효 🐰, 🎨 스타일

#136 [Feature] 비밀번호 변경 기능 및 프로필 관련 UI 개선, 버그 수정
  package-lock.json
  package.json
  src/features/Notification/NotificationContext.tsx
  src/features/auth/pages/ResetPasswordPage.tsx
  src/features/user/pages/profile/UserProfilePage.tsx
  src/features/user/pages/profile/components/ChangePasswordModal.tsx
  src/features/user/pages/profile/components/ChangePasswordModel.styled.ts
  src/layouts/Header/dropdown/ProfileDropdown.styled.ts
  src/layouts/Header/dropdown/ProfileDropdown.tsx
  src/layouts/Header/notification/NotificationDropdown.styled.ts
  src/layouts/Header/notification/NotificationDropdown.tsx
  src/layouts/Header/profile/UserProfile.styled.ts
  src/layouts/Header/profile/UserProfile.tsx
  src/layouts/Sidebar/Sidebar.styles.ts
  src/layouts/Sidebar/Sidebar.tsx
  src/layouts/Topbar/Topbar.tsx
  src/pages/CompanyPage.tsx
  src/pages/DashboardPage.tsx
  src/pages/MemberPage.tsx
  src/pages/ProjectPage.tsx
  src/pages/user/UserDashboardCards.styled.tsx
  src/pages/user/UserDashboardCards.tsx
  src/pages/user/styled.tsx
  src/pages/user/userDashboard.tsx
  src/styles/styles
  src/utils/utils
Labels: ♻️ 리팩토링, ✨ 기능 추가, 유진 🐱

#141 [Feature] 이력 상세조회 api 연동 및 ui 수정
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/admin/components/UserFilterButton.tsx
  src/features/admin/components/UserSelectionModal.tsx
  src/features/admin/pages/ActivityLogPage.styled.ts
  src/features/admin/pages/ActivityLogPage.tsx
  src/features/admin/services/activityLogService.ts
  src/features/admin/types/activityLog.ts
  src/features/admin/types/index.ts
Labels: ♻️ 리팩토링, 승우 🐯

#143 [Style] 회원/업체 관리 페이지의 UI와 텍스트를 전체적으로 통일
  src/components/Sidebar.tsx
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/admin/pages/ActivityLogPage.tsx
  src/features/admin/pages/DashboardPage.tsx
  src/features/admin/services/activityLogService.ts
  src/features/company/components/CompanyDetailModal/CompanyDetailModal.tsx
  src/features/company/components/CompanyEditModal/CompanyEditModal.tsx
  src/features/company/components/CompanyFilterBar.tsx
  src/features/company/components/CompanyRegisterModal/CompanyRegisterModal.tsx
  src/features/company/pages/CompanyDetailPage.tsx
  src/features/company/pages/CompanyPage.tsx
  src/features/project-d/pages/CreateProjectPage.tsx
  src/features/project-d/pages/EditProjectPage.tsx
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/ProjectCreateModal.tsx
  src/features/user/components/MemberEditModal/MemberEditModal.tsx
  src/features/user/components/MemberRegisterModal/MemberRegisterModal.tsx
  src/features/user/pages/MemberDetailPage.tsx
  src/features/user/pages/MemberPage.tsx
  src/features/user/pages/profile/UserProfilePage.tsx
  src/layouts/Sidebar/Sidebar.tsx
Labels: 승우 🐯, 🎨 스타일

#146 [Feature] 링크 첨부 기능 구현, 회원/업체 목록 ui 통일, 게시글/댓글 username 추가
  src/components/ClickableMentionedUsername.tsx
  src/components/MentionSuggestions.tsx
  src/components/MentionTextArea.tsx
  src/components/UserProfileDropdown.tsx
  src/features/admin/components/ActivityLogDetailModal.tsx
  src/features/board/components/Answer/components/AnswerItem.tsx
  src/features/board/components/Answer/hooks/useAnswerUtils.tsx
  src/features/board/components/Answer/pages/AnswerDetailModal.tsx
  src/features/board/components/Comment/hooks/useCommentUtils.tsx
  src/features/board/components/Post/components/DetailModal/CommentForm.tsx
  src/features/board/components/Post/components/DetailModal/CommentItem.tsx
  src/features/board/components/Post/components/DetailModal/PostHeader.tsx
  src/features/board/components/Post/components/DetailModal/PostLinks.tsx
  src/features/board/components/Post/components/DetailModal/ProjectPostDetailModal.tsx
  src/features/board/components/Post/components/DetailModal/ReplyItem.tsx
  src/features/board/components/Post/components/FormModal/FullScreenContentEditor.tsx
  src/features/board/components/Post/components/FormModal/PostFormModal.tsx
  src/features/board/components/Post/components/FormModal/components/ContentEditorSection.tsx
  src/features/board/components/Post/components/FormModal/components/LinkInputSection.tsx
  src/features/board/components/Post/components/FormModal/components/PostFormFields.tsx
  src/features/board/components/Post/pages/PostListPage.tsx
  src/features/board/components/Question/components/QuestionAnswerModal/components/QuestionItem.tsx
  src/features/project-d/pages/ProjectDetailPage.tsx
  src/features/project-d/services/postService.ts
  src/features/project-d/types/post.ts
  src/features/project-d/types/question.ts
  src/features/project/components/Board/ProjectBoard.styled.ts
  src/features/project/components/Board/ProjectBoard.tsx
  src/features/project/components/Progress/ProjectProgress.styled.ts
  src/features/project/components/Progress/ProjectProgress.tsx
  src/features/user/services/userService.ts
  src/hooks/useMention.ts
  src/hooks/useUserProfile.ts
Labels: ✨ 기능 추가, 승우 🐯

#164 [Refator] 프로젝트 상태 변수명 변경
  src/features/project/components/Card/ProjectCard.tsx
  src/features/project/components/List/ProjectFilterBar.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.tsx
  src/features/project/services/projectService.ts
  src/features/project/types/Types.ts
Labels: ♻️ 리팩토링, 진효 🐰

#165 [Feature] 권한별 버튼 display
  src/features/project/components/Header/ProjectHeader.tsx
  src/features/project/pages/ProjectListPage.tsx
Labels: ✨ 기능 추가, 진효 🐰

#169 [Feature] 프로젝트 단계 관리 기능 구현
  src/features/project/components/Progress/ProjectProgress.styled.ts
  src/features/project/components/Progress/ProjectProgress.tsx
  src/features/project/components/Progress/StepOrderModal.styled.ts
  src/features/project/components/Progress/StepOrderModal.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/services/projectService.ts
Labels: ✨ 기능 추가, 유진 🐱, 🎨 스타일

#170 [Feature] 금액 필드 추가 및 페이지 번호 제한
  src/features/project/components/ProjectCreateModal.tsx
  src/features/project/pages/ProjectDetailPage.tsx
  src/features/project/pages/ProjectListPage.styled.ts
  src/features/project/pages/ProjectListPage.tsx
Labels: ✨ 기능 추가, 진효 🐰
